version: '3.8'

services:
  codebase-intelligence:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    image: codebase-intelligence:latest
    container_name: codebase-intelligence-server
    restart: unless-stopped
    
    # Environment variables
    environment:
      - NODE_ENV=production
      - CI_LOG_LEVEL=info
      - CI_DATABASE_PATH=/app/data/analysis.db
      - CI_ENABLE_TELEMETRY=true
      - CI_PROJECT_PATH=/projects
      - CI_TEMP_DIR=/app/temp
    
    # Volumes for data persistence and project access
    volumes:
      # Project source code (read-only)
      - ./:/projects:ro
      # Persistent data storage
      - codebase-data:/app/data
      # Logs
      - codebase-logs:/app/logs
      # Configuration
      - ./config:/app/config:ro
      # Temporary files (optional, can use tmpfs)
      - codebase-temp:/app/temp
    
    # Optional: expose health check port
    ports:
      - "7346:7346"
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.25'
    
    # Health check
    healthcheck:
      test: ["CMD", "node", "-e", "
        const http = require('http');
        const req = http.request({
          hostname: 'localhost',
          port: 7346,
          path: '/health',
          timeout: 5000
        }, (res) => process.exit(res.statusCode === 200 ? 0 : 1));
        req.on('error', () => process.exit(1));
        req.end();
      "]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # Security options
    security_opt:
      - no-new-privileges:true
    read_only: false  # Set to true if you don't need to write to the container filesystem
    
    # Process limits
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      nproc:
        soft: 4096
        hard: 4096

  # Optional: Web UI service
  codebase-ui:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    image: codebase-intelligence:latest
    container_name: codebase-intelligence-ui
    restart: unless-stopped
    
    command: ["node", "dist/ui/WebServer.js"]
    
    environment:
      - NODE_ENV=production
      - CI_UI_PORT=7346
      - CI_API_URL=http://codebase-intelligence:7345
    
    ports:
      - "7346:7346"
    
    depends_on:
      - codebase-intelligence
    
    volumes:
      - codebase-data:/app/data:ro
      - codebase-logs:/app/logs:ro
    
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.1'

volumes:
  codebase-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data
  
  codebase-logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./logs
      
  codebase-temp:
    driver: tmpfs
    driver_opts:
      tmpfs-size: 100m

networks:
  default:
    name: codebase-intelligence-network